# Generated by Django 5.0 on 2024-11-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_management", "0015_alter_taskcategory_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyarticleselection",
            name="source",
        ),
        migrations.AddField(
            model_name="dailyarticleselection",
            name="claps_count",
            field=models.IntegerField(default=0),
        ),
    ]
